language: php

sudo: false

php:
  - 7.2
  - 7.3
#  - nightly

env:
  global:
  - COVERAGE=0
  matrix:
  - LARAVEL='6.0.*' TESTBENCH='4.0.*'
  - LARAVEL='7.0.*' TESTBENCH='5.0.*'

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  include:
  - php: 7.3
    env: COVERAGE=1 LARAVEL='7.0.*' TESTBENCH='5.0.*'
  exclude:
  - php: 7.3
    env: LARAVEL='7.0.*' TESTBENCH='5.0.*'

before_script:
  - composer config discard-changes true


before_install:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${LARAVEL}" "illuminate/database:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update


install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest


script:
  - if [[ $COVERAGE = '0' ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE = '1' ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi


after_script:
  - if [[ $COVERAGE = '1' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
